---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: NGOWebsite
spec:
 replicas: 2
 strategy: 
    type: RollingUpdate
 selector: 
   matchLabels: 
     app: ngo
 template:
  metadata:
   name: ngowebsitepod
   labels:
     app: ngo	 
  spec: 
    containers:
    - name: ngowebsitecontainer
      image: vicky2580/ngo
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: webappsvc
spec:
  type: NodePort
  selector:
   app: ngo
  ports:
   - port: 80
     targetPort: 8080
     NodePort: 3030
...
